### PR TITLE
Added tests and support for parsing 0 coordinates

### PR DESCRIPTION
**Pull request by Bradbev**
Fixes issue #25

### CODE REVIEW

**Comment by tmcw** [comment]
Thanks!

**Comment by Bradbev** [comment]
Hi Tom, what's the typical NPM publish cadence for wellknown please?
Thanks for the prompt merge.

**Comment by tmcw** [comment]
wellknown 0.3.4 is published on npm

**Comment by Bradbev** [comment]
Awesome!  Cheers!

**Pull request merged**
